package com.exifremoval;

import com.drew.imaging.ImageMetadataReader;
import com.drew.metadata.Directory;
import com.drew.metadata.Metadata;
import com.drew.metadata.exif.ExifIFD0Directory;
import com.drew.metadata.exif.ExifInteropDirectory;
import com.drew.metadata.exif.ExifSubIFDDirectory;
import com.drew.metadata.exif.ExifThumbnailDirectory;
import com.drew.metadata.exif.GpsDirectory;
import com.drew.metadata.exif.PrintIMDirectory;
import com.drew.metadata.icc.IccDirectory;
import com.drew.metadata.iptc.IptcDirectory;
import com.drew.metadata.photoshop.DuckyDirectory;
import com.drew.metadata.photoshop.PhotoshopDirectory;
import com.drew.metadata.xmp.XmpDirectory;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvFileSource;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assumptions.assumeFalse;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * Compares Java exif-removal output against exiftool reference outputs.
 *
 * For each test image with EXIF metadata:
 * - Asserts the Java output contains no sensitive metadata (GPS, IPTC, XMP, ICC, maker notes)
 * - Asserts orientation is preserved
 * - Asserts pixel data matches the exiftool reference (lossless formats only)
 *
 * For files without EXIF: asserts byte-identical copy (no processing).
 *
 * Reference outputs in expected-exiftool/ are pre-generated by generate-exiftool-expected.sh.
 */
class ExifToolComparisonTest {

    static final Path outputDir = Path.of("build/test-output/exiftool-comparison");

    @BeforeAll
    static void createOutputDir() throws Exception {
        Files.createDirectories(outputDir);
    }

    // ---- Metadata cleanliness: Java output has no sensitive metadata ----

    @ParameterizedTest(name = "metadata clean: {0}")
    @CsvFileSource(resources = "/testdata/metadata-ground-truth.csv", numLinesToSkip = 1)
    void testStrippedOutputHasNoSensitiveMetadata(
            String resourcePath, boolean hasExif, boolean hasGps, int orientation,
            boolean hasIptc, boolean hasXmp, boolean hasIcc, boolean hasMakerNotes) throws Exception {

        assumeTrue(hasExif || hasIptc, "Skipping file without EXIF or IPTC");

        File input = resourceFile(resourcePath);
        String base = basename(resourcePath);
        Files.copy(input.toPath(), outputDir.resolve(addSuffix(base, "_original")),
                StandardCopyOption.REPLACE_EXISTING);
        File output = outputDir.resolve(addSuffix(base, "_processed")).toFile();
        assertDoesNotThrow(() -> ExifRemoval.process(input, output),
                "Processing failed for " + resourcePath);

        Metadata metadata = assertDoesNotThrow(
                () -> ImageMetadataReader.readMetadata(output),
                "Failed to read metadata from output of " + resourcePath);

        // Collect all violations rather than failing on the first one
        List<String> violations = new ArrayList<>();

        checkAbsent(metadata, GpsDirectory.class, "GPS", violations);
        checkAbsent(metadata, ExifSubIFDDirectory.class, "EXIF SubIFD", violations);
        checkAbsent(metadata, ExifThumbnailDirectory.class, "EXIF Thumbnail", violations);
        checkAbsent(metadata, ExifInteropDirectory.class, "EXIF Interop", violations);
        checkAbsent(metadata, GpsDirectory.class, "GPS", violations);
        checkAbsent(metadata, IptcDirectory.class, "IPTC", violations);
        checkAbsent(metadata, XmpDirectory.class, "XMP", violations);
        // ICC is allowed in TIFF output (Java ImageIO injects sRGB during re-encoding)
        if (!isTiff(resourcePath)) {
            checkAbsent(metadata, IccDirectory.class, "ICC Profile", violations);
        }
        checkAbsent(metadata, PhotoshopDirectory.class, "Photoshop", violations);
        checkAbsent(metadata, DuckyDirectory.class, "Ducky", violations);
        checkAbsent(metadata, PrintIMDirectory.class, "PrintIM", violations);

        // Check that IFD0, if present, contains only orientation + structural tags
        ExifIFD0Directory ifd0 = metadata.getFirstDirectoryOfType(ExifIFD0Directory.class);
        if (ifd0 != null) {
            for (var tag : ifd0.getTags()) {
                int type = tag.getTagType();
                // Allowed: Orientation (0x0112), XResolution (0x011A), YResolution (0x011B),
                // ResolutionUnit (0x0128), YCbCrPositioning (0x0213), ImageWidth (0x0100),
                // ImageHeight/Length (0x0101), BitsPerSample (0x0102), Compression (0x0103),
                // PhotometricInterpretation (0x0106), SamplesPerPixel (0x0115),
                // RowsPerStrip (0x0116), StripByteCounts (0x0117), StripOffsets (0x0111),
                // PlanarConfiguration (0x011C), NewSubfileType (0x00FE)
                if (!isStructuralIFD0Tag(type)) {
                    violations.add("IFD0 contains non-structural tag: " + tag.getTagName()
                            + " (0x" + Integer.toHexString(type) + ")");
                }
            }
        }

        if (!violations.isEmpty()) {
            fail("Residual metadata in output of " + resourcePath + ":\n  - "
                    + String.join("\n  - ", violations));
        }
    }

    // ---- Orientation preserved ----

    @ParameterizedTest(name = "orientation preserved: {0}")
    @CsvFileSource(resources = "/testdata/metadata-ground-truth.csv", numLinesToSkip = 1)
    void testOrientationPreserved(
            String resourcePath, boolean hasExif, boolean hasGps, int orientation) {

        assumeTrue(hasExif, "Skipping file without EXIF");
        assumeTrue(orientation > 1, "No non-trivial orientation to preserve");
        assumeFalse(isTiff(resourcePath), "TIFF applies orientation as pixel transform");

        File input = resourceFile(resourcePath);
        File output = outputDir.resolve(addSuffix(basename(resourcePath), "_processed")).toFile();
        assertDoesNotThrow(() -> ExifRemoval.process(input, output));

        Metadata metadata = assertDoesNotThrow(
                () -> ImageMetadataReader.readMetadata(output));

        ExifIFD0Directory ifd0 = metadata.getFirstDirectoryOfType(ExifIFD0Directory.class);
        assertNotNull(ifd0, "EXIF IFD0 missing in output of " + resourcePath);
        assertTrue(ifd0.containsTag(ExifIFD0Directory.TAG_ORIENTATION),
                "Orientation tag missing in output of " + resourcePath);
        assertEquals(orientation, ifd0.getInteger(ExifIFD0Directory.TAG_ORIENTATION),
                "Orientation value mismatch for " + resourcePath);
    }

    // ---- Pixel fidelity: lossless formats match exiftool reference ----

    @ParameterizedTest(name = "pixel fidelity: {0}")
    @CsvFileSource(resources = "/testdata/metadata-ground-truth.csv", numLinesToSkip = 1)
    void testPixelFidelityMatchesExiftool(
            String resourcePath, boolean hasExif, boolean hasGps, int orientation,
            boolean hasIptc) throws Exception {

        assumeTrue(hasExif || hasIptc, "Skipping file without EXIF or IPTC");
        assumeFalse(isTiff(resourcePath), "TIFF re-encodes differently");
        assumeFalse(isWebp(resourcePath), "WebP pixel comparison requires webp-imageio");

        File input = resourceFile(resourcePath);
        File javaOutput = outputDir.resolve(addSuffix(basename(resourcePath), "_processed")).toFile();
        ExifRemoval.process(input, javaOutput);

        String exiftoolPath = resourcePath.replace("input/", "expected-exiftool/");
        File exiftoolRef = resourceFile(exiftoolPath);

        BufferedImage javaImg = ImageIO.read(javaOutput);
        BufferedImage exiftoolImg = ImageIO.read(exiftoolRef);

        assertNotNull(javaImg, "Failed to decode Java output for " + resourcePath);
        assertNotNull(exiftoolImg, "Failed to decode exiftool reference for " + resourcePath);

        assertEquals(exiftoolImg.getWidth(), javaImg.getWidth(),
                "Width mismatch for " + resourcePath);
        assertEquals(exiftoolImg.getHeight(), javaImg.getHeight(),
                "Height mismatch for " + resourcePath);

        double rmse = computeRMSE(exiftoolImg, javaImg);
        assertEquals(0.0, rmse, 1e-9,
                "Pixel mismatch between Java and exiftool output for " + resourcePath
                        + " (RMSE=" + rmse + ")");
    }

    // ---- No-op: files without EXIF are byte-identical copies ----

    @ParameterizedTest(name = "no-op copy: {0}")
    @CsvFileSource(resources = "/testdata/metadata-ground-truth.csv", numLinesToSkip = 1)
    void testNoExifFilesCopiedUnchanged(
            String resourcePath, boolean hasExif, boolean hasGps, int orientation,
            boolean hasIptc) throws Exception {

        assumeFalse(hasExif, "Only testing no-EXIF files");
        assumeFalse(hasIptc, "Only testing no-IPTC files");

        File input = resourceFile(resourcePath);
        File output = outputDir.resolve(addSuffix(basename(resourcePath), "_processed")).toFile();
        ExifRemoval.process(input, output);

        assertArrayEquals(
                Files.readAllBytes(input.toPath()),
                Files.readAllBytes(output.toPath()),
                "File without EXIF should be byte-identical copy: " + resourcePath);
    }

    // ---- Helpers ----

    private static void checkAbsent(Metadata metadata, Class<? extends Directory> dirType,
                                    String name, List<String> violations) {
        Directory dir = metadata.getFirstDirectoryOfType(dirType);
        if (dir != null && dir.getTagCount() > 0) {
            List<String> tags = new ArrayList<>();
            dir.getTags().forEach(t -> tags.add(t.getTagName()));
            violations.add(name + " still present with tags: " + tags);
        }
    }

    private static boolean isStructuralIFD0Tag(int tagType) {
        // Tags that describe image structure, not content metadata
        return tagType == 0x0100  // ImageWidth
                || tagType == 0x0101  // ImageHeight/Length
                || tagType == 0x0102  // BitsPerSample
                || tagType == 0x0103  // Compression
                || tagType == 0x0106  // PhotometricInterpretation
                || tagType == 0x0111  // StripOffsets
                || tagType == 0x0112  // Orientation
                || tagType == 0x0115  // SamplesPerPixel
                || tagType == 0x0116  // RowsPerStrip
                || tagType == 0x0117  // StripByteCounts
                || tagType == 0x011A  // XResolution
                || tagType == 0x011B  // YResolution
                || tagType == 0x011C  // PlanarConfiguration
                || tagType == 0x0128  // ResolutionUnit
                || tagType == 0x0213  // YCbCrPositioning
                || tagType == 0x00FE; // NewSubfileType
    }

    private static boolean isTiff(String resourcePath) {
        return resourcePath.endsWith(".tiff") || resourcePath.endsWith(".tif");
    }

    private static boolean isWebp(String resourcePath) {
        return resourcePath.endsWith(".webp");
    }

    private static String basename(String resourcePath) {
        int slash = resourcePath.lastIndexOf('/');
        return slash >= 0 ? resourcePath.substring(slash + 1) : resourcePath;
    }

    private static String addSuffix(String filename, String suffix) {
        int dot = filename.lastIndexOf('.');
        return filename.substring(0, dot) + suffix + filename.substring(dot);
    }

    private File resourceFile(String path) {
        var url = getClass().getClassLoader().getResource(path);
        assertNotNull(url, "Test resource not found: " + path);
        return new File(url.getFile());
    }

    private static double computeRMSE(BufferedImage a, BufferedImage b) {
        int w = a.getWidth(), h = a.getHeight();
        long sumSq = 0, count = 0;
        for (int y = 0; y < h; y++) {
            for (int x = 0; x < w; x++) {
                int rgbA = a.getRGB(x, y), rgbB = b.getRGB(x, y);
                int dr = ((rgbA >> 16) & 0xFF) - ((rgbB >> 16) & 0xFF);
                int dg = ((rgbA >> 8) & 0xFF) - ((rgbB >> 8) & 0xFF);
                int db = (rgbA & 0xFF) - (rgbB & 0xFF);
                sumSq += dr * dr + dg * dg + db * db;
                count += 3;
            }
        }
        return Math.sqrt((double) sumSq / count) / 255.0;
    }
}
